version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: somedudesbot
      POSTGRES_USER: postgres
      POSTGRES_DB: somedudes
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    links:
      - "db"
  bot:
    build: ./frontend
    restart: always
    links:
      - "backend"
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
